[package]
name = "common"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
pnet = "*"
prost = "*"
rand = "*"
num-traits = "*"
num-derive = "*"

[build-dependencies]
prost-build = "*"
