[package]
name = "spacy_plugin"
version = "0.1.0"
edition = "2021"

[lib]
name = "spacy_plugin"
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
pyo3 = { version = "*", features = ["extension-module"] }
nix = "*"
